# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: gameMapPool
  id: SS220MapPool
  maps:
  - Frankenstein
# - Nox # Removed until rework
  - Axioma
  - Eclipse
  - Donuts
