- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # SS220-RoleTime
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos #SS220-Transfer Detective To Security
  canBeAntag: false #SS220-Transfer Detective To Security
  access:
  - Brig
  - Maintenance
  - Service
  - Detective
#  extendedAccess: #SS220-Transfer Detective To Security
  - Security
  - Cryogenics 
  special: #SS220-Transfer Detective To Security begin
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] #SS220-Transfer Detective To Security end

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    neck: ClothingBeltHolsterFilled #SS220 holster to neck
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
