// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.RoundEnd.UI;

[GenerateTypedNameReferences]
public sealed partial class RoundEndTitlesSection : Control
{
    private const float WidthThreshold = 700;

    public RoundEndTitlesSection()
    {
        RobustXamlLoader.Load(this);
    }

    public RoundEndTitlesSection(string title, Texture? icon, int columns = 1) : this()
    {
        TitleLabel.Text = title;
        IconRect.Texture = icon;
        RolesContainer.Columns = columns;
    }

    protected override void Resized()
    {
        var isMarginsEnabled = Width >= WidthThreshold;
        ListMarginLeft.Visible = isMarginsEnabled;
        ListMarginRight.Visible = isMarginsEnabled;
    }
}
